### ISSUE TITLE
Form in fieldset

### ISSUE THREAD

**Issue by TessaViergever** [sannevanseeventer/the-web-is-for-everyone-interactive-functionality#1]
Hi (:

Volgens mij hoort <fieldset> binnen de <form> tag.

https://github.com/sannevanseeventer/the-web-is-for-everyone-interactive-functionality/blob/547dbc431e7a09332d6fa061e2d8ec28451b3e30/views/noteForm.ejs#L3

**Comment by sannevanseeventer** [comment]
Dankjewel voor je issue, ik heb het aangepast! :)
